name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake libxft-dev libxinerama-dev libxcursor-dev  \
        libxfixes-dev libpango1.0-dev libpangoxft-1.0-0 libpangocairo-1.0-0
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Build
      env:
          RUST_BACKTRACE: 1
      run: cargo build --release
    - name: Compress binary
      run: upx --best --lzma target/release/perlink
      continue-on-error: true
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/perlink
        token: ${{ secrets.GITHUB_TOKEN }}